### ISSUE TITLE
Update "cs"

### ISSUE THREAD

**Issue by Akari79** [northwood-studios/SCPSL-Translations#122]
Hello, 
Just wanted to update Czech translation
good to mention that it's not "cs" but "cz" 

Delete cz translation from Krumpac. It's extremly outdated and he is no longer playing SCPSL
Thanks!
http://www.mediafire.com/folder/qe7vj1xws1sb0/Czech_(Čeština)_by_Akari

Best Regards,
ahyper/Akari

**Comment by MichalPetryka** [comment]
"cs" is the correct tag for Windows https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c

**Comment by Akari79** [comment]
Yes - my bad. Coding in CB and default is cz from tabs. Sorry!
