### ISSUE TITLE
Update localization files for new game design features

### ISSUE THREAD

**Issue by bladuk** [northwood-studios/SCPSL-Translations#1261]
Femur breaker is removed from the game. His mention should also be removed from the loading hints. https://github.com/northwood-studios/SCPSL-Translations/blob/f12b36f1cc129f171833c497b324d58190f6ebc1/Translations/English%20(default)/LoadingHints.txt#L50

Сan we call the new SCP-939's attack a "bite"? https://github.com/northwood-studios/SCPSL-Translations/blob/f12b36f1cc129f171833c497b324d58190f6ebc1/Translations/English%20(default)/LoadingHints.txt#L55-L56

SCP-939 can't sprint indefinitely https://github.com/northwood-studios/SCPSL-Translations/blob/f12b36f1cc129f171833c497b324d58190f6ebc1/Translations/English%20(default)/LoadingHints.txt#L57

SCP-939 not inflicts amnesia upon humans it bites https://github.com/northwood-studios/SCPSL-Translations/blob/f12b36f1cc129f171833c497b324d58190f6ebc1/Translations/English%20(default)/LoadingHints.txt#L56

SCP-049 can't kill any human instantly https://github.com/northwood-studios/SCPSL-Translations/blob/f12b36f1cc129f171833c497b324d58190f6ebc1/Translations/English%20(default)/LoadingHints.txt#L60

Weapon manager is removed from the game.
https://github.com/northwood-studios/SCPSL-Translations/blob/de06c5ff7ab033db78c04586d520dc79c7cd2248/Translations/English%20(default)/Version_7-0-0.txt#L2-L5

**Comment by SpeedyOW** [comment]
This also goes for the File Version_7-0-0.txt Which has 4 lines referencing the weapon manager tablet, altough the item is no longer available

**Comment by LazarOroz** [comment]
> This also goes for the File Version_7-0-0.txt Which has 4 lines referencing the weapon manager tablet, altough the item is no longer available
> 
> 
> 
> 

Still important due to the YOU DIED translation being fetched from that file I think

**Comment by bladuk** [comment]
Added, thanks

**Comment by LazarOroz** [comment]
Why don't we remove it ourselves? They are always random for the tips and the weapon manager file we just remove everything but YOU DIED

**Comment by bladuk** [comment]
Yes, we can. But TranslatorChecker test will be failed. It just compares lines count in translation files with the original English translation. PR with failed checks can't be approved.
![chrome_ENTMJeoNFl](https://user-images.githubusercontent.com/68610520/209409798-420a6210-c1cf-4662-b9df-a8230185a02e.png)

**Comment by bladuk** [comment]
Also we can't make commits to default translation.
![chrome_ml6SbdMX7G](https://user-images.githubusercontent.com/68610520/209410268-87cb5eaa-d374-4ba9-a251-616d47cdb51c.png)

**Comment by LazarOroz** [comment]
ok

**Comment by Rnen** [comment]
I'll submit this to development staff. English changes needs to happen at their discretion.
Please await removal of translated lines until English gets their changes, as otherwise there will be both issues and confusion.

**Comment by Rnen** [comment]
Main issue here being, the translation system for the game is rather old and is thus based on line numbers.
So if we would remove a line from the english translation, all other translations would suddenly display the wrong line.

**Comment by bladuk** [comment]
Perhaps the better solution would be make the game's translations similar to steam translations (where "tokens" are used, and changing a line in the file won't affect the entire translation as a whole).
However, this is indeed a major change and it will require a complete update of all current translations.

Steam translation I'm talking about:
![chrome_2AS5V0fS21](https://user-images.githubusercontent.com/68610520/209793149-8828f737-8bad-4e9c-87c0-fc05fc521caf.png)

**Comment by Rnen** [comment]
We are already planning on reworking the translations to a Key-Value type system, but is is a rather extensive process. 🙂
