### ISSUE TITLE
"Dark mode"- description in the main menu options isn't translateable

### ISSUE THREAD

**Issue by Red-Z** [northwood-studios/SCPSL-Translations#1264]
### Contact Details

Red Z#5555

### What happened?

Reposting this issue which has been reported on trello here:
https://trello.com/c/pUmOCBTL/4700-dark-mode-options-description-isnt-translateable

In short, in MainMenu.txt, Line 101, you can put the translation for the dark mode description. However, it will not use it
![SCPSL_EIf7xDQ0u8](https://user-images.githubusercontent.com/108956930/209352361-990cde11-3284-4e55-b94f-0f73a67877e3.png)

### Game Version

12.0

### Relevant log output

```shell
Missing translation! MainMenu 101 Toggle to change some bright elements to their dark-themed version.
Missing **FALLBACK** translation! MainMenu:101. Default value: Toggle to change some bright elements to their dark-themed version. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

### Code of Conduct

- [X] I agree to follow this Code of Conduct while interacting with this repo

**Comment by Dr-Ham** [comment]
Noted
