### ISSUE TITLE
There are no subtitles for event CASSIE messages

### ISSUE THREAD

**Issue by bladuk** [northwood-studios/SCPSL-Translations#1272]
### Contact Details

bladuk.#5642

### What happened?

For some events (e.g. Halloween, Christmas), CASSIE messages change, but subtitles for them don't. So subtitles display incorrect information.

### Game Version

12.0

### Code of Conduct

- [X] I agree to follow this Code of Conduct while interacting with this repo

**Comment by mortalsito** [comment]
I don't think it's a bug, but it would be better if they implemented subtitles for this class of events c:

**Comment by Dr-Ham** [comment]
Noted
