### ISSUE TITLE
Chaos bio is not correct

### ISSUE THREAD

**Issue by Firething** [northwood-studios/SCPSL-Translations#1323]
### Contact Details

Firething#0537

### What happened?

Chaos biography are the same as MTF's.

![image](https://user-images.githubusercontent.com/88356202/230697918-1afecd88-874e-4922-bdb7-fa7d7eeffa50.png)
![image](https://user-images.githubusercontent.com/88356202/230697952-e14e8568-bfdd-449b-8bcf-1d23eb6d56a5.png)

### Game Version

12.0

### Code of Conduct

- [X] I agree to follow this Code of Conduct while interacting with this repo

**Comment by Tychus-Xiaoyi** [comment]
That's an already known bug, but thanks for your report
