### ISSUE TITLE
Double ".txt" extension on some Spanish files

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#144]
Hi there,I was revisiting the ES translations and some of them have a double ".txt" . Something like "inventoryIssues.txt.txt" , I don't know the reason of that but they will not work on the game for sure. 

Edit : The files are  " InventoryErrors.txt.txt " and "  MenuWarnings.txt.txt "

**Comment by MichalPetryka** [comment]
Wait, actually some of them actually do have double extensions

**Comment by ConnorTheCone** [comment]
Yes, I don't know if i can fix it with a pull request or something, Do you have any idea why these two have the bouble extension?

**Comment by Dat-Joseph** [comment]
issue is resolved. Seems like you either added one .txt behind the two files manually or something went wrong in another way. Simply removed one of the .txt ending of the two.
