### ISSUE TITLE
Using Crowdin for the community translations

### ISSUE THREAD

**Issue by Fido2603** [northwood-studios/SCPSL-Translations#163]
Hello, I think a great addition to the development, and for easier usage for other users, would be if we switched from GitHub to Crowdin, which is a service for crowdsourced translations.
On Crowdin there are translators, and there can also be assigned proofreaders, who usually are native speakers of the languages to make sure that the translations are okay.

Crowdin is free for open source, but otherwise it costs on a basis of how many source strings are in the project, like 500 source strings for $16 a month.

**Comment by Dat-Joseph** [comment]
We will take a look into it, thank you for the suggestion. 👍
