### ISSUE TITLE
missing item type

### ISSUE THREAD

**Issue by SchrodingerSig** [northwood-studios/SCPSL-Translations#186]
Line 4 from InventoryErrors.txt
"You have now reached the limit of items of this type: <color=yellow>{0}</color> ({1}/{1})"

I guess "{0}" supporst be item type (like healing item, weapon, keycard or something) but i didnt actually find them... can someone add them? 🤔

**Comment by SchrodingerSig** [comment]
hmmmmmm? 🤔

**Comment by ConnorTheCone** [comment]
This is what you mean? 

The screenshoot has the spanish languaje,but is"You have reached the limit of items of this type"

![imagen](https://user-images.githubusercontent.com/50555272/69466802-d2ff9c80-0d85-11ea-86c8-295aa05ef6ef.png)

**Comment by SchrodingerSig** [comment]
> This is what you mean?
> 
> The screenshoot has the spanish languaje,but is"You have reached the limit of items of this type : "
> 
> ![imagen](https://user-images.githubusercontent.com/50555272/69466802-d2ff9c80-0d85-11ea-86c8-295aa05ef6ef.png)

yeah "Medical Item" is till in English

**Comment by SchrodingerSig** [comment]
its probably fine for languages that use 26 english letters
but its kind a big deal for non-english languages like Chinese or Japanese (etc) 🤔

**Comment by ConnorTheCone** [comment]
Some texts are no translated no matter the language, or at least I didn't find out how to translate it.

Texts like "Remaining targets" on the SCPs screen or some SCP-079 interface info.

Or all the door texts ( open, closed, moving, evacuate, locked down)

**Comment by Dat-Joseph** [comment]
These texts are not included yet in our translation repo. 
But I am fairly sure we will add those in the future to translate too. I cannot tell you when though.

**Comment by Dat-Joseph** [comment]
Also, the {0}/{1} are code lines. These numbers will be replaced ingame with text, those texts arent included yet too.

**Comment by SchrodingerSig** [comment]
uh... thats why im asking if someone can include the text of them so we can traslate them (btw i know how {0} works so thanks)
anyway, roger that
