### ISSUE TITLE
Thai coding bugs. 

### ISSUE THREAD

**Issue by DatPanDat** [northwood-studios/SCPSL-Translations#188]
One of my friend sent me a attached image showing that some parts of the menu are displaying blocks instead of the anticipated texts. My colleague (AGKK Histoire) told me that this is because of the code. May I ask what unicode does scpsl supported? 
![bugged](https://user-images.githubusercontent.com/49842082/68672090-cb9bf000-0548-11ea-9c8d-50a1de7c15f3.png)

**Comment by DatPanDat** [comment]
I should added that Thai support unicode is UTF-8 and UTF-16

**Comment by Rnen** [comment]
Which spesific game version was this?
Please include a screenshot of the debug info. (either F2 or F3 ingame)

**Comment by DatPanDat** [comment]
![unknown-3](https://user-images.githubusercontent.com/49842082/69044377-bad9f700-09ec-11ea-97a8-d251f58e7e2e.png)

**Comment by ShingekiNoRex** [comment]
Hey, sorry for the delay. We have added a list of thai characters to the game. But some are still missing. Can you take a look at it, and provide us a full list if possible?

List of characters:
`!"#'()*+,-./0123456789:;<=>?ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]_abcdefghijklmnopqrstuvwxyz{}ÂâĀāĪīǍǎɕʔːचथदनमरस्กขฃคฅฆงจฉชซญฏฐฒณดตถทธนบปผฝพฟภมยรลวศษสหฬอฮะัาำิีึเแโใไๆ็่้๏๛ḌḍḤḥṆṇṬṭ–—`

In-game screenshots:
https://media.discordapp.net/attachments/422385982235475968/649521498180288522/unknown.png
https://media.discordapp.net/attachments/422385982235475968/649521529805340672/unknown.png?width=1248&height=702

**Comment by DatPanDat** [comment]
May I ask what font are you guys using?

**Comment by ShingekiNoRex** [comment]
> May I ask what font are you guys using?

NotoSansThai-Regular.ttf

**Comment by DatPanDat** [comment]
Will it be hard to change the font? Because the problem might be coming from the font used. Histoire recommend using NotoSansThai-unhinted

**Comment by ShingekiNoRex** [comment]
> Will it be hard to change the font? Because the problem might be coming from the font used. Histoire recommend using NotoSansThai-unhinted

could you send me that font?

**Comment by DatPanDat** [comment]
[Mega link](https://mega.nz/#!y1dyhAjY!Mh0xeRqyRLWRpeKioxHp8lEV9kxOHJQpPLn-k1Cd6aI)

**Comment by ShingekiNoRex** [comment]
They are still missing.
![1](https://user-images.githubusercontent.com/36476262/69812246-abe41780-122a-11ea-83c4-9204dab16f44.png)
![2](https://user-images.githubusercontent.com/36476262/69812247-abe41780-122a-11ea-9827-a79c96afac72.png)
![3](https://user-images.githubusercontent.com/36476262/69812248-abe41780-122a-11ea-989f-8486fde94b46.png)

**Comment by DatPanDat** [comment]
Well darn. By looking at the images, I think these ones and the missing characters.

![IMG_20191128_213648](https://user-images.githubusercontent.com/49842082/69816161-bdf49480-11ef-11ea-95dc-66dd0a6cfe36.png)

![IMG_20191128_215620](https://user-images.githubusercontent.com/49842082/69816162-be8d2b00-11ef-11ea-9cd2-c5d3e11721ac.jpg)

The missing characters in the second image is more important through. Also, in the settings box where it said "การตั้งค่า" at ตั้ง. It shouldn't looks like that. I think  ัั or  ้้  is overlapping. I will try to get a solutions for this tomorrow after discussion with Histoire.

**Comment by folkza80** [comment]
I'm not sure how to solve it, but we try to offer them a try.
https://gist.github.com/allfake/d4fde9c573eaa4d5461a07ad446faf18

**Comment by DatPanDat** [comment]
Also death causes didn't showed up properly when I was using thai language.
![700330_screenshots_20191130222107_1](https://user-images.githubusercontent.com/49842082/69909380-bd781b80-13f2-11ea-8dce-969cb3525b10.jpg)

**Comment by DatPanDat** [comment]
So er... Any luck?

**Comment by DatPanDat** [comment]
Hello? Anyone?

**Comment by Dat-Joseph** [comment]
Hey there, im new to this thread. 
It is very likely that the problems youre having, are fixed in our next patch. 
If you have any further questions or problems, feel free to @ me :D

**Comment by DatPanDat** [comment]
I've ask one of my friend to check their patreon build to is if it was fixed about 4 hours ago. Some of the places like server browsers showed up with no problems. But somewhere else like the settings and pre game menu still have the same problems. I'll list all the problems I've seen so far in the pictures in a moment.

**Comment by DatPanDat** [comment]
[An imgur album link](https://imgur.com/a/OQqUoOY) that list all the problem we've seen so far.

**Comment by DatPanDat** [comment]
@Dat-Joseph I forgot to tag you. Soz.

**Comment by Dat-Joseph** [comment]
Thank you, we will take a look into it and try to resolve your issue with the best of our abilities. 
It may take some time for us to find the issue and respond to you. Its not forgotten though :)

**Comment by DatPanDat** [comment]
Now that 10.0.0 is released and I could play it, I'll try to make a video and try to record every broken letters, vowels, and syllables I may find.

**Comment by DatPanDat** [comment]
Updates: I do not have enough time due to how many encoding bugs there is. But most of the problems seem to be the same as before. And sometimes some work, sometimes they don't.

**Comment by MichalPetryka** [comment]
@DatPanDat Does this look ok?
![image](https://user-images.githubusercontent.com/35800402/88585217-187e1300-d053-11ea-808b-0d99db7ef779.png)

**Comment by DatPanDat** [comment]
@MichalPetryka The menu is the least broken part, but there's still some visual error. For example, at the friend tab. The tone marks is overlapping inside vowel, so its looks like เพือน instead of เพื่อน, ที is supposed to be ที่, and เชือม is supposed to be เชื่อม. But most of the players can guess what it's supposed to mean, through. The problem is that sometimes it will shows a square box instead like the info box or the abilties menu.

**Comment by Dat-Joseph** [comment]
About the square boxes, sorry for the late reply, we are working with unity devs to fix this issue about misdisplayed fonts or missing characters.
