### ISSUE TITLE
Question about 939 bio.

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#207]
Hello there, the bio of SCP-939 say than 939 is silent, but, in the curren version of the MP2 it make sounds walking and running. 

Is something not implemented yet or the translation is wrong?

**Comment by Dat-Joseph** [comment]
as far as i can tell, (by playing the beta) SCP-939 does make noise. But only while sprinting. Normal walking (no sprint) does not produce any sound.

**Comment by ConnorTheCone** [comment]
I see, thanks for the clarification, maybe i was wrong.
