### ISSUE TITLE
arabic

### ISSUE THREAD

**Issue by bara9880** [northwood-studios/SCPSL-Translations#265]
are you guys interested in an arabic translation ? can the game show arabic characters in the correct form ?

**Comment by Rnen** [comment]
Arabic would be great!
Although i suggest checking if MP2 can handle the characters with a few sentences, before creating the entire translation. :slightly_smiling_face: 
In the case of missing characters, we can figure out a solution.

**Comment by bara9880** [comment]
This might sound dump , but I'm new to git hub , is there any video or a simple explanation on how to start ? And how can I test a couple of lines before translating the while thing

**Comment by Rnen** [comment]
Copy your english game translation, rename the copy to the fitting arabic language code located [Here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
Then change some lines in your new copy to some arabic text, and try it ingame.
The main [README ](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) should explain a lot about using GitHub, and links to some other tutorials.

**Comment by bara9880** [comment]
![Screenshot_20191201-171242_Chrome](https://user-images.githubusercontent.com/58350309/69916660-fbf6f000-145d-11ea-9f14-31fdadccc5de.jpg)

Got it ! I'll keep you posted once I try it later

**Comment by bara9880** [comment]
![image](https://user-images.githubusercontent.com/58350309/69949638-3611d180-14f2-11ea-980f-2a91587d78f8.png)

maybe unity does not support arabic ?

**Comment by bara9880** [comment]
it needs something called 'Arabic-Support-for-Unity-UI"

https://github.com/AbdullahAlimam/Arabic-Support-for-Unity-UI

**Comment by bara9880** [comment]
it does recognise its arabic , but its written in the opposite direction ,and the letters arent holding each other, it should be " العربية "
![image](https://user-images.githubusercontent.com/58350309/69950545-c7ce0e80-14f3-11ea-8ea7-e66a726578a2.png)

**Comment by bara9880** [comment]
"short answer : unity doesn't support Arabic or Persian although there are bunch of plugins on assets store that can buy you some times. you can find them easily." sad

**Comment by Dat-Joseph** [comment]
It has been 3/4 of a year. Maybe you could try again? I am unsure if the issue has been fixed with newer Unity versions. Though, im sure its worth a try.
