### ISSUE TITLE
uk

### ISSUE THREAD

**Issue by Wenyanngat** [northwood-studios/SCPSL-Translations#345]
Usually a domain **uk** this is the United Kingdom. The right domain is **ua** Ukraine
Please fix it.

**Comment by MichalPetryka** [comment]
Uk is the correct tag for Windows

**Comment by Rnen** [comment]
`ua` is not a valid culture identifier. See [Microsoft Language Tags](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c) for more info.
