### ISSUE TITLE
Updating source files and translations

### ISSUE THREAD

**Issue by Rayfulrand** [northwood-studios/SCPSL-Translations#434]
Hi guys. I'm new here and got confused.

Files here (English default) are different from the ones I get in Steam version.
I've retranslated the game into Ukrainian (previous translation had many mistakes and it was only 40% translated, so I edited them). But I've tried to use translated files from here in the game, and most variables simply don't work. Then I compared English files with Steam English version and updated my translations according to those files.

My questions is, which version should I pull here?
Also, there are quite many lines in the game, that are not in translation files. How comes?

Thank you for your time and answers.

**Comment by Dat-Joseph** [comment]
Hey there,
to make it very simple. Always translate after whats here on GitHub. Variables change in the text files while compiling (as i know it). To be on the safe side, use the current english default on github, not the public version on steam. The steam translation is missing files which are needed in our next patch. If you have any other questions, feel free to ask.

**Comment by Rayfulrand** [comment]
Thank you, @Dat-Joseph. Everything is aligned with Github version, I've doubled checked translations and made pull request for Ukrainian (with last update of abilities).

**Comment by Dat-Joseph** [comment]
Ayy, no problem. We will take a look at it. Thank you for contributing 👍
