### ISSUE TITLE
i have an issue with mainmenu.txt

### ISSUE THREAD

**Issue by despacitosimulator** [northwood-studios/SCPSL-Translations#441]
Whenever I try to translate mainmenu.txt and then encode, I get some weird symbols that change everything I wrote. Am I doing something wrong or is this intentional? It does this only on mainmenu.txt
![image](https://user-images.githubusercontent.com/48863157/79116868-3c626500-7d92-11ea-81a2-0435e6b5b456.png)

**Comment by Dat-Joseph** [comment]
What do you exacly mean by encode? And in what language are you translating?

**Comment by despacitosimulator** [comment]
I'm translating English to Bulgarian and by encode I mean that I use the program provided by Northwood that makes sure everything is working or something like that.

**Comment by Dat-Joseph** [comment]
We dont actually have any program that encodes text files as far as i know. 
The best thing for you would be to edit your translation not locally but rather here on the website.

**Comment by despacitosimulator** [comment]
Ok, gonna move my translations to my repository
