### ISSUE TITLE
SCP-079 light containment zone incorrect camera name

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#458]
Hi there, i don't know if this is a translation thing but there is a bug on the 079 Light contamint zone checkpoint what shows an incorrect name for the room on the top left corner.

I share a video to show what i'm trying to say : https://youtu.be/Bmo81fmJgWY 

In the video you can see how i'm on elevator system A but when i move the camera forward to the Checkpoint of elevator system A it says what i'm on elevator checkpoint B, the same on ther other elevator system. As i said, i don't know if this is a translation thing, i didn't see any folder for the 079 corridors names. Well, thanks.

**Comment by Dat-Joseph** [comment]
Thank you for telling us. It is not in the translations, rather hardcoded into the game as far as i know. I will forward this to the right person. Again thanks for it 👍

**Comment by ConnorTheCone** [comment]
If it helps i think what is just a wrong seed generation. I mean, it atlways happen but i don't know. Well, i'm glad to help.
