### ISSUE TITLE
Need early access

### ISSUE THREAD

**Issue by EsquiloVoador** [northwood-studios/SCPSL-Translations#477]
I am translating the new scophophobia update and to check if it is good, I need to wait for the game to be released, which ends up being very time consuming and ineffective, so I would like to know if I could get access to the early access version.

**Comment by Dat-Joseph** [comment]
I am sorry to inform you that this is infact very much not possible. 
Everyone would need access to the early beta version and this would be very unfair to our helpful patrons. I can assure you though that you can translate everything that is currently here on the repo. The testing can be done when the beta will be publicly available.
