### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by Rayfulrand** [northwood-studios/SCPSL-Translations#513]
Hi guys. When can we expect translation update? Several months past, but I don't have any answer and don't see any updates for several languages at all, though they have pull requests for several months as well.

Can you create a separate channel in Discord where we could discuss localization issues?

Thank you

**Comment by ConnorTheCone** [comment]
I like the idea of a channel in Discord

**Comment by Dat-Joseph** [comment]
Connor is right, the easiest way to explain the delay is that we lack native translators.
We currently have only a few in Northwood who are native and trustworthy translators. This is why some languages are updated so frequently and often. 
As an example, we lack many native speakers like korean, spanish, italian etc etc...
We really need time and feedback from multiple people, due to that. 
Google Translator (or any other) isnt really a reliable source of correct translations, which is why we prefer human checks. I am the german translator at northwood and i for my part chose to only check german / austrian if possible. In our earliest days we had problems that people changed languages who didnt even speak it, and thats just wrong. 

The only really thing i can say is, that we are sorry for the delay. We try our best to work with you guys and we all appreciate your help.

**Comment by ConnorTheCone** [comment]
Who is the Spanish speaker? The only one from Northwood what i know what is from Spain is Killer1001, he was Global moderator.

**Comment by Tychus-Xiaoyi** [comment]
Hello,please allow me to reply instead of our manager.We discussed the idea some time ago,but translation team need to talk to the community management, believe than the outcome of the discussion will be available soon

**Comment by Dat-Joseph** [comment]
I do not know who Killer1001 is. As far as i can see, he does not work at Northwood anymore. 
Also, i believe we do not have any native spanish speakers in the studio.

**Comment by Rayfulrand** [comment]
Thank you for your answers, team.
I understand that all I need to do now is waiting.

P.s: Still voting for Discord channel, where we can at least discuss issues, not translated things that are in game now and talk with other translators and responsible for translations manager (or team) from Northwood Studios, I think it can be closed one with separate role "Translator" to access there. And at first you can add this role to translators that can prove they are translators (like showing their branches) or something like that.

**Comment by ConnorTheCone** [comment]
I miss read your first comment and because that I thought what you said what Nw has native Spanish speakers. Well, I do my best to keep the Spanish translation up to date.

Killer1001 was global moderator, now he isn't.

**Comment by Rayfulrand** [comment]
HI @ConnorTheCone,
sorry for bothering you again. I've just pushed new updates and read again your last answer to me.

> As an example, we lack many native speakers like korean, spanish, italian etc etc...
> We really need time and feedback from multiple people, due to that.

But... how will you receive feedbacks on Ukrainian if it's not in game? Currently, people somehow need to find out that there is Ukrainian language on GitHub, go there, download, insert into game folder and then test. Maybe it's good to ask players somewhere in Discord and list languages that require such check?

In other way it's endless loop where you wait for feedbacks from players that don't know the game is translated to their language.

As for Ukrainian, I did my best to provide the best quality. I'm game localizer and editor with many years of experience and more than 70 finished projects in Ukrainian already: https://steamcommunity.com/id/Rayfulrand

Also, it will be easier to track changes when at least current state of my translation will be merged because the previous one was awful (Google Translated) and only 30% were translated. I made translation from scratch from English and keep updating all your updates. Also, I've added Steam presence, achievements, badges translations etc.

Could you please merge my translations? I would announce it and invite some more people for testing (it was already tested as much is possible, but some things simply can't be added manually from my side, only by you).

**Comment by ConnorTheCone** [comment]
I don't know why you ping me, i mean, i'm not a Northwood employee or member either, i can't help you with that, i just help with the Spanish translations.

You can know who are the people what manage the NW github [here](https://github.com/orgs/northwood-studios/people) , or at least members of it, i don't know how it works .

And as i said before 

> Sometimes they take time to check the translations, probably because they don't speak that languaje or well, i don't know, i don't work on northwood.

Maybe you should try to send a email to Evan for translations stuff, even the thing of creating a channel to the translation info, i like that idea. Well, have a nice day.

**Comment by Dat-Joseph** [comment]
> But... how will you receive feedbacks on Ukrainian if it's not in game? Currently, people somehow need to find out that there is Ukrainian language on GitHub, go there, download, insert into game folder and then test. Maybe it's good to ask players somewhere in Discord and list languages that require such check?

We usually search for players who are native in the specifiied language, e.g. here it would be Ukranian. 
The Discord Channel is till being discussed on as it is not "in our hands" (different Department). 

> Could you please merge my translations? I would announce it and invite some more people for testing (it was already tested as much is possible, but some things simply can't be added manually from my side, only by you).

If you know other people who are native ukranians, please tell us who. This would speed up the merge progress vastly.

**Comment by ConnorTheCone** [comment]
> 
> We usually search for players who are native in the specifiied language, e.g. here it would be Ukranian.
> The Discord Channel is till being discussed on as it is not "in our hands" (different Department).
> 

Well, if you need help with the ES translations you can md me, send an email or md on discord. I'm on the SL discord but normally i don't talk.

**Comment by Rayfulrand** [comment]
@Dat-Joseph thank you!
Should I write their Discord names?

**Comment by Dat-Joseph** [comment]
If you'd be so kind. It really helps us alot

**Comment by Rayfulrand** [comment]
@Dat-Joseph 
Sorry for delay, here are three users that agreed to share their contacts:
Sergii «Fallenbard» Raboshchuk#6144
Іван „John_Hawk“ Бачинський#8302
AngryCossackUA#8271

Also, everyone asks when text will be fully translated as there are many not translated things that I can't find on GitHub

**Comment by Dat-Joseph** [comment]
Thank you, ill get in touch with them as soon as im able to. 

about the other untranslatable ones...
We cant do much about it, its a programmers task. In the future though, near all texts will be translatable
