### ISSUE TITLE
Idea - Put the Class name as a variable

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#514]
I suggest to put the class name with his colour as a variable like messages of "Wait x to use y".

Because writing all the time for example <color=#f00>SCPs</color> or whatever the class is can make you had some errors or diferent names.

I think what something like [classD] , [scientist] , [guard] , [939](or whatever the scp number is) , [mtfCadet] , [mtfLT] , [mtfCMD] can be fine if the class has the colour and the name. Maybe right now you think what is a waste of time because there are a lot of translations and all of them are done by this way but i think what future translations and for saving text can be fine.

**Comment by Dat-Joseph** [comment]
I dont believe this is possible due to Unity Rich Text. Thank you for the suggestions though. I'll try to forward it to the correct person :)

**Comment by ConnorTheCone** [comment]
I see, i never tryied to get variables from a text file on Unity but i though what it was the same as the [ammo] , [time] and [item] stuff

**Comment by Rnen** [comment]
Yeah like mentioned ,
The semi-html `<color> / <size> / ect.` that unity does in its Rich-Text is completely separate from our game variables `[varName]`
Also, due to translations, auto-coloring the words as "SCP" and such would not be viable.
But thanks for the suggestion though!
