### ISSUE TITLE
Conection errors has multiple lines for the same?

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#515]
I was checking to see if i missed something on the ES translations and i saw what the file [Conections_Errors.txt](https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/English%20(default)/Connection_Errors.txt) on the Default version has some lines what seems to be duplicated. 

For example.

Line 7 & 8 say exactly the same
**Line 7** <size=80>DISCONNECTED</size>\nConnection lost (timed out).
**Line 8** <size=80>DISCONNECTED</size>\nConnection lost (timed out).

Line 10 & 17 both say what your game version and the server version are not the same
**Line 10**<size=80>DISCONNECTED</size>\nYour game version is different from the server.
**Line 17**<size=80>VERSION INCOMPATIBILITY</size>\nYour game version is different from the server\n(Client - [your]; Server - [server])

And the same for all the Bans lines. Each ban has two lines, one what say "You has been banned" and other what say "You has been banned: reason" and sometimes there is also the time

**Line 23** <size=80>DISCONNECTED</size>\nYou have been globally banned.
**Line 24** <size=80>DISCONNECTED</size>\nYou have been globally banned: [reason].

**Line 25** <size=80>DISCONNECTED</size>\nYou have been banned from this server.
**Line 26** <size=80>DISCONNECTED</size>\nYou have been banned from this server.\nBan expires: [date] [time]

**Line 32** <size=80>DISCONNECTED</size>\nYou have been banned from this server.\nReason: [reason]
**Line 33** <size=80>DISCONNECTED</size>\nYou have been banned from this server.\nBan expires: [date] [time]\nReason: [reason]

I though what the reason is why some bans are permanent and other some bans doesn't had any reason especified. If that is the reason why not add other lines wich say "Reason not especified by the staff" or something like that and for the ban "Perma banned" or just "Undefined" ? If that is the reason of the duplicated lines i think what doing this you will save some lines.

**Comment by Dat-Joseph** [comment]
If im correct, there really isnt a set maximum of lines in a file to read from. We can add as many as we want. Still thank you for opening this issue 👍 

There is a reason for these "duplicates". Lets just take a look at your last example, the first (line 32) will be displayed if you're perm-banned on the server (which is why you dont need a date and time), the second (line 33) will be displayed when you're banned but not permanently.

**Comment by ConnorTheCone** [comment]
Yes, i understand the reason of the duplicated texts. But as the same what you can put the time why not pick a string what say "Perma banned" for the perma bans? For example. You have been banned from this server. Expires: "Never" or "Permanently banned"

I think what you can use only two lines. One for the global bans "You have been globally banned: [reason]." and the other for server bans  "You have been banned from this server. Ban expires: [date] [time] Reason: [reason]"

Adding other two lines at the end with "Unspecified" when the server Staff didn't put a reason and "Permanently banned" for perma bans.
