### ISSUE TITLE
Now I found broken texts

### ISSUE THREAD

**Issue by OneKoin** [northwood-studios/SCPSL-Translations#516]
![캡처](https://user-images.githubusercontent.com/63756421/85962366-5273df00-b9eb-11ea-976e-4b91ad34c758.PNG)
Like the image above, some of those korean characters are broken and are now blanks.
Will it be fixed automatically? Or is it a problem with fonts?

**Comment by Tychus-Xiaoyi** [comment]
Thanks for your report, this issue has been submitted to our developers,we regret for the inconvenient caused :)

**Comment by horyu1234** [comment]
+1

I have same issue in public release (Scopophobia)

**Comment by OneKoin** [comment]
Not only those words in the picture uploaded, but also words in game tips, user name, etc are broken

**Comment by Tychus-Xiaoyi** [comment]
fixed,please wait for the next patch update

**Comment by OneKoin** [comment]
When does this applied? Is this still on testing phase?

**Comment by MichalPetryka** [comment]
Going to be released in 11.0.
