### ISSUE TITLE
Epsilon 11 Instead Nine Tailed fox is also correct?

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#556]
Hi there, i want to know if for the MTF units is correct to use "Epsilon 11" instead "Nine Tailed Fox" more or less because Epsilon 11 is the name of the task force and Nine Tailed Fox seems more a nick name. You can see it on the [WIki](http://www.scp-wiki.net/task-forces#epsilon-11)

I think what the correct way should be change the NTF to Epsilon 11 and add Nine tailed fox to the nick name folder. And as i remember CASSIE say "Mobile task force Epsilon 11"

**Comment by Rnen** [comment]
I think this far, most english text uses "Nine tailed fox" as thats the more iconic and recognizable option over the two.
For now i think we should stick to that.
