### ISSUE TITLE
Is it able to change korean fonts?

### ISSUE THREAD

**Issue by OneKoin** [northwood-studios/SCPSL-Translations#557]
![20200729_210413.png](https://user-images.githubusercontent.com/63756421/88797997-2496db80-d1df-11ea-9081-23fb96ba7386.png)

English fonts are neat and clean as the picture above.
Also the fonts are consistent.

![20200729_210642.png](https://user-images.githubusercontent.com/63756421/88798177-78092980-d1df-11ea-9483-e7f4243a2ab5.png)

However, korean fonts by the way, some letters have a shallow box over them, and the fonts are inconsistent so they look disorganized.

**Comment by Tychus-Xiaoyi** [comment]
Hello,we have noticed this problem, please waiting for our fix pack

**Comment by OneKoin** [comment]
@Tychus-Xiaoyi ![20200729_230443.png](https://user-images.githubusercontent.com/63756421/88810122-e81fab80-d1ef-11ea-850b-c6ddb9a16846.png)

Plus, those two underlined(which are yellow and white) letters' font style are different. Please make those font styles unified.

Thanks again.

**Comment by Tychus-Xiaoyi** [comment]
Our programmers plan to probably unify it into NotoSans

**Comment by OneKoin** [comment]
thanks :)

**Comment by Tychus-Xiaoyi** [comment]
Thanks for your tracking and feedback on SCPSL❤

**Comment by MichalPetryka** [comment]
Reopening since it isn't fixed yet

**Comment by OneKoin** [comment]
@Tychus-Xiaoyi [https://drive.google.com/file/d/1sDq_R17YUYdCiOq6gUhUKNxPV1pP6fY8/view?usp=drivesdk](LINK)
Can you ask the developers to try this font if they can? Of course this is for free for all, allowing commercial use and modification.

**Comment by MichalPetryka** [comment]
Does this look good? @OneKoin 
![unknown (1)](https://user-images.githubusercontent.com/35800402/98940404-3892ee80-24eb-11eb-87fd-4a68c9774231.png)

**Comment by OneKoin** [comment]
**Better.**

**Comment by MichalPetryka** [comment]
Are there any issues? Is something displayed incorrectly?

**Comment by OneKoin** [comment]
Nope. It's just perfect, nothing wrong.
