### ISSUE TITLE
Translation not applied in verified server

### ISSUE THREAD

**Issue by OneKoin** [northwood-studios/SCPSL-Translations#569]
![20200803_131933.png](https://user-images.githubusercontent.com/63756421/89145633-55369680-d58c-11ea-9661-b8475a20a137.png)
The picture above is from nondedicated server,

![20200803_131947.png](https://user-images.githubusercontent.com/63756421/89145651-64b5df80-d58c-11ea-9824-3a424c18bbc0.png)
and this is from verified server "103.143.32.76:7777"

![20200803_134806.png](https://user-images.githubusercontent.com/63756421/89146858-f7a44900-d58f-11ea-99df-a6a66c674032.png)
this from verified server "218.55.211.132:7777"

Even though both game is using same translation file, same language option(korean), while nondedicated server is showing Korean translation, public server is showing English translation.

Is this because of the server settings? or is it a problem with the game?

**Comment by ConnorTheCone** [comment]
I think what the game has a bug, since before MP2, what do that.

I mean, before the MP2 i was testing my translations, on my private server worked but on a public server it happened the same what on your screenshoots, i think what that is not a config, because the translations are client side.

I have the same bug with the ES (Spanish) translations.

**Comment by OneKoin** [comment]
> I think what the game has a bug, since before MP2, what do that.
> 
> I mean, before the MP2 i was testing my translations, on my private server worked but on a public server it happened the same what on your screenshoots, i think what that is not a config, because the translations are client side.
> 
> I have the same bug with the ES (Spanish) translations.

So. korean was not the only language that are no applied in public server, right?

Maybe if the staff watches this, i think they will solve this problem.

**Comment by ConnorTheCone** [comment]
As far as i know is a game bug i think, isn't the first time what someone posted about this i think. I think what is a bug, but i'm not sure right now. But i can guarantee what i had that same bug with my translations.

**Comment by sirmeepington** [comment]
As far as I know, the translations for death reasons are determined on the server, and the dedicated server uses the English translation.

**Comment by zabszk** [comment]
Death reasons are currently in the language of the server and dedicated servers always use English. It's reported as a bug and will be fixed.

**Comment by OneKoin** [comment]
Got it. thanks for informing :)

**Comment by ConnorTheCone** [comment]
> 
> 
> As far as I know, the translations for death reasons are determined on the server, and the dedicated server uses the English translation.

So, changing the translation files from the server will change that? As far i remember i think what there is a translation folder on the server and it only has English.

I think what server side translations will be a good add on to the game (As option). I mean, some servers have other kind of rules and changing that via server cand be handy.

**Comment by zabszk** [comment]
We are not planning to make server-side translations, because server doesn't know the language of the users. Death reasons being translated server-side is a bug and will be fixed.

**Comment by ConnorTheCone** [comment]
> 
> 
> We are not planning to make server-side translations, because server doesn't know the language of the users. Death reasons being translated server-side is a bug and will be fixed.

Yeah, but the thing with that is what normally you host a sever on one language and the people who join speak the same language. I mean, if you host an English server you want English speakers, if i go to that server speaking spanish i'm probably going to be banned. The same with other languages.

But i understand your point. Thanks for the comment.

**Comment by Dat-Joseph** [comment]
While you do have a point, imagine the following.
There are people who prefer to use the english translation that then localized. I've met many players from germany who prefer English over German as its most common to them (cause they mostly play other games in english aswell). So Serverside translations would hinder you from using the translation you want.

**Comment by OneKoin** [comment]
Yeah I agree with zabzsk and joseph.
In Korea, many of users use English cause they think Korean fonts are not better than English fonts.
Also, users should choose words by themselves not depending on servers config.

**Comment by zabszk** [comment]
> 
> 
> While you do have a point, imagine the following.
> There are people who prefer to use the english translation that then localized. I've met many players from germany who prefer English over German as its most common to them (cause they mostly play other games in english aswell). So Serverside translations would hinder you from using the translation you want.

I'm from Poland, but I play games in English, because usually that's the one of the best translations (and many games aren't even translated to Polish).

**Comment by ConnorTheCone** [comment]
> 
> 
> While you do have a point, imagine the following.
> There are people who prefer to use the english translation than the localized. I've met many players from germany who prefer English over German as its most common to them (cause they mostly play other games in english aswell). So Serverside translations would hinder you from using the translation you want.

Yeah, i understad. Thanks for the replies, in my case i prefeer the Spain Spaish always except when the game is half translated or something like that.

**Comment by zabszk** [comment]
Issue should be resolved by the update (version 10.0.2) that was released last week.
