### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by SoulMercer** [northwood-studios/SCPSL-Translations#606]
[https://hizliresim.com/TgUkd0](url)
''inşallah'' arabic word
Actually ''tekrar hoşgeldiniz''
I'll be glad if you fix it

**Comment by OneKoin** [comment]
You should edit the translation file by yourself.
The file you should edit is "translations/TR/NewMainMenu.txt".
Check the 66th line and edit them as you want.

Before editting please read README file or the github repository's details.
