### ISSUE TITLE
About Door.txt,

### ISSUE THREAD

**Issue by OneKoin** [northwood-studios/SCPSL-Translations#654]
In Korean, the translated text is quite small compared to English ones.

I wonder if you put size tag in the textfile so that users can manage the size of the text.

**Comment by Tychus-Xiaoyi** [comment]
You can use `size=`content `/size` to adjust the fonts size, but unity rich text temporarily doesn't work for workstation,weaponmods, DecontaminationDisplays.txt

**Comment by OneKoin** [comment]
Yeah I knew how to resize the text by unity rich text, but I wanted to know if it is possible on official translation.

**Comment by Tychus-Xiaoyi** [comment]
You can use `size=`content `/size` to adjust the fonts size, but unity rich text temporarily doesn't work for workstation,weaponmods, DecontaminationDisplays.txt

> Yeah I knew how to resize the text by unity rich text, but I wanted to know if it is possible on official translation.

Yea,of course. 
All translation text for the best game experience and content accuracy as the goal.
So please check and test the translation in the game before pull request 😁

**Comment by Tychus-Xiaoyi** [comment]
> Yeah I knew how to resize the text by unity rich text, but I wanted to know if it is possible on official translation.

Yea,of course.
All translation text for the best game experience and content accuracy as the goal.
So please check and test the translation in the game before pull request 😁

**Comment by OneKoin** [comment]
Thank you for your help :)
