### ISSUE TITLE
Regarding steam announcements. 

### ISSUE THREAD

**Issue by DatPanDat** [northwood-studios/SCPSL-Translations#66]
So after today's steam announcements. I realise that there is either no steam announcements translation or there isn't any steam announcements Thai translator. Is there any way to opt in to translate steam announcements or is it isn't planned?

**Comment by Dat-Joseph** [comment]
I havent received any info else for steam translations. Else there would be a german too. But im sure its being discussed

**Comment by DatPanDat** [comment]
I agreed and hope it got approved. It could bring more audiences in translated countries.

**Comment by Dogera** [comment]
Heya, Steam Manager here, we haven't been translating the announcements for a bit now, we've usually just taken willing staff members to translate them. For now, if you want your Steam news translation, you can friend me on Steam and I'll give you a link to a document with the formatting and then you send me it back translated
https://steamcommunity.com/id/4rae/

**Comment by DatPanDat** [comment]
Sent the invite. Thanks for the response!

**Comment by Dat-Joseph** [comment]
closing this issue now :)
