### ISSUE TITLE
Abilities -> Lockdown wrong description

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#75]
Hey, I downloaded the last translation to translate the added documents to spanish and reading the abilities doc founded some wrong descriptions.

The SCP-079 can lockdown the rooms at tier 2 but in the new doc say "Tier 3".
It also say than the generators need "Two minutes " to be engaged but in the actually gameplay is 1 minute and 30 seconds, and "The only way to kill 079 is 5 generators" but it can be killed with the Alpha warhead too

They are errors or addons of the new update? I don't know but i don't what to write wrong descriptions and thats why i'm posting this post.

edit: I checked again the generator countdown and it is 2 min, my fault.

Thanks.

**Comment by Rnen** [comment]
We'll be looking into it shortly. :+1:

**Comment by ConnorTheCone** [comment]
Okey, i will wait to finish the translation. 


Thanks.

**Comment by realmbmc** [comment]
Any news regarding this issue? Maybe it will change next update? Or do we need to fix it in our own translations?

**Comment by Dat-Joseph** [comment]
Im sorry if i cant answer your question correctly. You would need to fix the translations on your own, be sure to check latest updates on the current english translation. Edit the things that are wrong, and do not forget that the lines have to match 1:1. If youre done you can request a Pull-request. We will then check your translation for any errors (like wrong lines, example line 66 is in your spanish translations line 67.) If everything looks right we will merge it. If i recall it correctly these translations will be public when Mega Patch Part 2 goes live.

**Comment by realmbmc** [comment]
Ok, let me explain correctly.
Currently, SCP-079 gain lockdown ability at Access Level 2, but in game translation file it says that he needs to gain Access Level 3 instead. I am not sure if I need to correct it to Level 2 in my own localization OR SCP-079 will actually get this ability on Level 3 in Mega Patch Part 2. This needs to be clarificated.

**Comment by ConnorTheCone** [comment]
Thats the point. They didn't say anything about nerfing the lockdowns.

**Comment by Dat-Joseph** [comment]
I would just plain suggest you go after what is currently in the default english translation. 
We can always change it if its still wrong 😄

**Comment by Rnen** [comment]
Ideally we'll make the number of access level a variable that will be filled automatically if we haven't already for MP2/MP3. So if we'd make number modifications later down the line, translations would automatically adapt.
