### ISSUE TITLE
Item's name fit issue | Version 11.0 Patreon Beta 

### ISSUE THREAD

**Issue by REALMWTH** [northwood-studios/SCPSL-Translations#778]
If I don't use new line (\n) between two parts of keycard's name, it looks awful
![image](https://user-images.githubusercontent.com/1342847/125357681-3cbc2800-e368-11eb-9067-be90e7b4decd.png)
But if I add new line tag (\n) it looks like that
![image](https://user-images.githubusercontent.com/1342847/125357731-4c3b7100-e368-11eb-977d-53e00717dafb.png)
I think you guys should change text align to center like it was before.

**Comment by Rnen** [comment]
Forwarded together with https://github.com/northwood-studios/SCPSL-Translations/issues/779
Thanks! :smile:

**Comment by Rnen** [comment]
Should be fixed i believe, feel free to reopen if the issue persists in later versions
