### ISSUE TITLE
Missed translation lines | Version 11.0 Patreon Beta

### ISSUE THREAD

**Issue by REALMWTH** [northwood-studios/SCPSL-Translations#779]
1) Ammo type in weapon's and armor's descriptions are not translateable
![image](https://user-images.githubusercontent.com/1342847/125357868-7d1ba600-e368-11eb-8117-4db2a43e12d9.png)

2) CI Rifleman, Repressor and Maradeur's descriptions are not translateable
![image](https://user-images.githubusercontent.com/1342847/125357949-9b81a180-e368-11eb-91fa-86f4f763a554.png)

3) Workstation is not translateable
![image](https://user-images.githubusercontent.com/1342847/125357989-a805fa00-e368-11eb-9baa-4f22166ca526.png)
![image](https://user-images.githubusercontent.com/1342847/125357998-a9cfbd80-e368-11eb-870e-e07136719a0c.png)
![image](https://user-images.githubusercontent.com/1342847/125358004-accaae00-e368-11eb-86c6-17104ff272b1.png)
![image](https://user-images.githubusercontent.com/1342847/125358025-b227f880-e368-11eb-8217-819a15ec5f61.png)

**Comment by Rnen** [comment]
Thanks! Looking into it

**Comment by Rnen** [comment]
Just out of curiosity
Is there good reason to have the ammunition translatable?

**Comment by REALMWTH** [comment]
Not at all if it's too difficult ;)

**Comment by Rnen** [comment]
Closing this for now, the missing translations are WIP features which will get their full translatable content by release.
Thanks for reporting though!
