### ISSUE TITLE
In game texts without translation 

### ISSUE THREAD

**Issue by ConnorTheCone** [northwood-studios/SCPSL-Translations#812]
There are some of the texts that i saw in game that doesn't have any way to translate it.

- Elevator system texts (A and B)
- Idle and loading Workstation creen
- Some 079 interfaces (Room name, access tier text, stop transmiting [Speaker], fast camera switch [That thing in the top-right corner ])
- Player list (Username, badge and actions)
- Remote admin
- Texture quality dropdown
- Controls hotkeys, inspect
- Server configuration (Friendly Fire, Modded, Official)
- 079 generators
- Change the weapon attachements during spectator text
- Spectator access tier (When spectating 079)
- Press ESC to disconnect on the loading screen
- In game escape menu (Continue, Server info, Settings, disconnect)
- (Not sure about this one) The rectangle that appears when joining on "On Waiting for players" has a text explaining how to open the player list, i think that is not translated.
- When you are kicked
- SCP Remaining targets texts
- Please wait on the loading screen
- Synchronizes the frame rate of a game with a gaming monitor's refresh rate.
- Smoothes lines and removes visual distortions.
- Applies soft shadows to corners and tight areas to give models more depth.
- Projected textures such as bullet holes or blood splatter.
- Gives the environment more depth at a high performance cost.
- Gives lighting more depth by applying a glow based on the light intensity.
- Flashes the taskbar when you spawn while the game is not in focus.
- READ THE PRIVACY POLICY
- Enter IP/Hostname
- "HP" at health bar

**Comment by schade61** [comment]
\+ When you are kicked

![KickedWithNoReason](https://user-images.githubusercontent.com/84141055/127766880-be3a632b-e40b-4cf4-8f84-7ed57f7572ec.png)
![KickedWithReason](https://user-images.githubusercontent.com/84141055/127767004-2cbd27b2-512d-47f4-9231-65701551a039.png)

**Comment by ConnorTheCone** [comment]
Added

**Comment by Cezhar16** [comment]
Hi, these texts still can't be translated.In the settings there is an explanation of the functions and neither of them can be translated , I attach two screenshots plus I can't translate how many targets are left, and when loading the game "please wait"

everything marked in red
Thanks

![vysvetleni](https://user-images.githubusercontent.com/77750216/128643767-561f404d-0ebb-4bc8-93e2-2e8741e434e0.png)
![vysvetleni1](https://user-images.githubusercontent.com/77750216/128643768-d3e1769b-42ef-4edd-939e-e7a1be92dd55.png)
![targets](https://user-images.githubusercontent.com/77750216/128643771-b0345a4d-aa25-49b0-bdf0-3f37dcd50422.png)
![loading](https://user-images.githubusercontent.com/77750216/128643778-525436ab-9032-422e-a75a-053348cebaf2.png)

**Comment by schade61** [comment]
> Hi, these texts still can't be translated.In the settings there is an explanation of the functions and neither of them can be translated , I attach two screenshots plus I can't translate how many targets are left, and when loading the game "please wait"
> 
> everything marked in red
> Thanks
> 
> ![vysvetleni](https://user-images.githubusercontent.com/77750216/128643767-561f404d-0ebb-4bc8-93e2-2e8741e434e0.png)
> ![vysvetleni1](https://user-images.githubusercontent.com/77750216/128643768-d3e1769b-42ef-4edd-939e-e7a1be92dd55.png)
> ![targets](https://user-images.githubusercontent.com/77750216/128643771-b0345a4d-aa25-49b0-bdf0-3f37dcd50422.png)
> 

Check line 70, 85 on[https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/English%20(default)/MainMenu.txt](MainMenu.txt) for those two translations.

**Comment by schade61** [comment]
> ![vysvetleni](https://user-images.githubusercontent.com/77750216/128643767-561f404d-0ebb-4bc8-93e2-2e8741e434e0.png)
> ![vysvetleni1](https://user-images.githubusercontent.com/77750216/128643768-d3e1769b-42ef-4edd-939e-e7a1be92dd55.png)
> 

Did you try translating [MainMenu.txt](https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/English%20(default)/MainMenu.txt) for those two?

**Comment by MajorFox-MJ** [comment]
> Hi, these texts still can't be translated.In the settings there is an explanation of the functions and neither of them can be translated , I attach two screenshots plus I can't translate how many targets are left, and when loading the game "please wait"
> 
> everything marked in red
> Thanks
> 
> ![vysvetleni](https://user-images.githubusercontent.com/77750216/128643767-561f404d-0ebb-4bc8-93e2-2e8741e434e0.png)
> ![vysvetleni1](https://user-images.githubusercontent.com/77750216/128643768-d3e1769b-42ef-4edd-939e-e7a1be92dd55.png)
> ![targets](https://user-images.githubusercontent.com/77750216/128643771-b0345a4d-aa25-49b0-bdf0-3f37dcd50422.png)
> ![loading](https://user-images.githubusercontent.com/77750216/128643778-525436ab-9032-422e-a75a-053348cebaf2.png)

You can translate those in this file :
Cf https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/cs/MainMenu.txt

**Comment by ConnorTheCone** [comment]
Added (Please wait and Remaining targets)

**Comment by Cezhar16** [comment]
> > Hi, these texts still can't be translated.In the settings there is an explanation of the functions and neither of them can be translated , I attach two screenshots plus I can't translate how many targets are left, and when loading the game "please wait"
> > everything marked in red
> > Thanks
> > ![vysvetleni](https://user-images.githubusercontent.com/77750216/128643767-561f404d-0ebb-4bc8-93e2-2e8741e434e0.png)
> > ![vysvetleni1](https://user-images.githubusercontent.com/77750216/128643768-d3e1769b-42ef-4edd-939e-e7a1be92dd55.png)
> > ![targets](https://user-images.githubusercontent.com/77750216/128643771-b0345a4d-aa25-49b0-bdf0-3f37dcd50422.png)
> > ![loading](https://user-images.githubusercontent.com/77750216/128643778-525436ab-9032-422e-a75a-053348cebaf2.png)
> 
> You can translate those in this file :
> Cf https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/cs/MainMenu.txt

Lol thanks , i didnt see this

**Comment by Blueberryy** [comment]
"HP" at health bar is also doesn't support translations.

**Comment by ConnorTheCone** [comment]
Added, thanks.

**Comment by Rnen** [comment]
I've forwarded this to the Bug hunting team (QA).
For any future simmilar cases, report it at https://support.scpslgame.com/bug-report
:slightly_smiling_face:
