### ISSUE TITLE
chaos Armed&Dangerous text

### ISSUE THREAD

**Issue by SpeedyOW** [northwood-studios/SCPSL-Translations#904]
when pressing F1 as a chaos (any subclass) has the ability armed n dangerous which says you have consigned a LMG, altough this is not true with parabellum due to AK, revolver and shotgun so i just wanted to sugest for it to change depending on what subclass you spawn as.

https://gyazo.com/629ebdebfa28f48de761198bea426940 (image of text)

**Comment by Rnen** [comment]
I've forwarded this to the Bug hunting team (QA).
For any future simmilar cases, report it at https://support.scpslgame.com/bug-report
:slightly_smiling_face:
