### ISSUE TITLE
106 tab GUI diacritic bug

### ISSUE THREAD

**Issue by SpeedyOW** [northwood-studios/SCPSL-Translations#909]
when having the tab menu opened as 106, if you do not have your cursor on anything it will use the most recent text, but if you hover your mouse over one of the 2 options diacritics appear as invisible, im not sure what causes it and it happens for every romanian diacritic

diacritics: ă î â ș ț    Ă Î Â Ș Ț

video demonstration:  https://www.youtube.com/watch?v=HfqH5uR6-s8

**Comment by Rnen** [comment]
I've forwarded this to the Bug hunting team (QA).
For any future simmilar cases, report it at https://support.scpslgame.com/bug-report
:slightly_smiling_face:
