### ISSUE TITLE
(SCP-330) Scrambled names/descrıptıons.

### ISSUE THREAD

**Issue by Gonsez** [northwood-studios/SCPSL-Translations#952]
Hello, I have a problem wıth SCP-330. Candy names and descrıptıons (even the candy bag's descrıptıon. It has green candy's descrıptıon) are scrambled ın Turkısh currently. I don't know how that happened, lınes on GıtHub are ın same order.
![CandyBagGreen](https://user-images.githubusercontent.com/57308562/148229303-b914df41-454d-4bc1-9e60-3c0b2ea7429a.jpg)
![RaınbowYellowCandy](https://user-images.githubusercontent.com/57308562/148229326-f898ad28-97c1-496e-8f33-86a8ef755a08.jpg)
![Red](https://user-images.githubusercontent.com/57308562/148229340-cc228387-be23-48e4-a841-bd3e3eec1f50.jpg)

[SCP-330 TR](https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/tr/SCP330.txt)

That happens on Turkısh but I don't know maybe other languages have that ıssue too. Thanks.

**Comment by Rnen** [comment]
I've forwarded this to the Bug hunting team (QA).
For any future simmilar cases, report it at https://support.scpslgame.com/bug-report
:slightly_smiling_face:
