### ISSUE TITLE
German Translation for "History" in the Server-Menu is "false"

### ISSUE THREAD

**Issue by MrNeonM** [northwood-studios/SCPSL-Translations#978]
So when you are in the main menu and on the server browser, in the german translation the tab for the history of previously joined servers is "Historie". This is a word-to-word translation, which doesn't quite work in this context. 
There's multiple words for "history" in german, a lot of them, including "Historie", actually mean "story", or, in the case of Historie, also historical science or world history. So it doesn't imply that it's the server history. A better word for it would be "Verlauf", which is what the browser history is called too, for example. That's basically the word for something that keeps track of something that happened, which, in this case, would be the correct wording.
I've included a picture of the word

![image](https://user-images.githubusercontent.com/85352424/151452104-b6d056c8-02ed-4b67-9db4-b8ef186a16d3.png)

**Comment by Dat-Joseph** [comment]
Hey! Danke für den Hinweis.
Ich bin mir selber unschlüssig warum Ich Historie als Begriff, anstelle von Verlauf, genutzt habe. 
In meinem aktuellen PR habe Ich diesen Fehler behoben, dieser sollte dann im nächsten Update ( vorausgesetzt das PR wird zeitnah gemerged) nicht mehr aufzufinden sein.

**Comment by MrNeonM** [comment]
> Hey! Danke für den Hinweis. Ich bin mir selber unschlüssig warum Ich Historie als Begriff, anstelle von Verlauf, genutzt habe. In meinem aktuellen PR habe Ich diesen Fehler behoben, dieser sollte dann im nächsten Update ( vorausgesetzt das PR wird zeitnah gemerged) nicht mehr aufzufinden sein.

Passt, vielen Dank!
